feat: bsm oauth api 개발
recuritup/cheerup-server pull request #4
Opened 2023-11-05 15:28 UTC by SEOKKAMONI

## ⛳️작업 내용
bsm oauth를 연결하여 로그인 api를 개발하였습니다.

## 📎레퍼런스

2023-11-05 15:47 UTC, qlido requested changes
LNGTM

2023-11-05 15:47 UTC, qlido commented on prisma/schema.prisma
> +  id          Int     @id @unique
Why is @id and @unique together

2023-11-05 15:47 UTC, qlido commented on src/controller/AuthContoller.ts
> +import * as AuthService from '../service/AuthService';
why don't you use absolute path

2023-11-05 15:47 UTC, qlido commented on src/service/AuthService.ts
> +console.log(BSM_AUTH_CLIENT_SECRET);
? delete plz

2023-11-05 15:47 UTC, qlido commented on src/service/AuthService.ts
> +const BSM_AUTH_CLIENT_SECRET = process.env.CLIENT_SECRET || '';
env variable must be write with error handling expression

2023-11-05 15:47 UTC, qlido commented on src/service/AuthService.ts
> +  const authCode = req.query.code;
why don't you write with destructuring assignment

2023-11-05 15:47 UTC, qlido commented on src/service/AuthService.ts
> +        let userRole: Role = 'STUDENT';
you can Role.student

2023-11-05 15:47 UTC, qlido commented on src/service/AuthService.ts
> +      }
Plz early return

2023-11-05 15:47 UTC, qlido commented on src/controller/AuthContoller.ts
> +router.post('/', AuthService.loginUser);
I think authService has too much responsibility

2023-11-05 15:50 UTC, SEOKKAMONI commented on src/controller/AuthContoller.ts
> +import * as AuthService from '../service/AuthService';
들여쓰기 된다 많아지면 나는 싫다 보기

2023-11-05 15:50 UTC, SEOKKAMONI commented on src/service/AuthService.ts
> +console.log(BSM_AUTH_CLIENT_SECRET);
고맙다 매우

2023-11-05 15:51 UTC, qlido commented on src/controller/AuthContoller.ts
> +import * as AuthService from '../service/AuthService';
..쓰지 말라니까 뭔소리하노

2023-11-05 15:52 UTC, SEOKKAMONI commented on src/controller/AuthContoller.ts
> +import * as AuthService from '../service/AuthService';
아 부족했다 영어실력 나의

2023-11-05 15:52 UTC, SEOKKAMONI commented on src/controller/AuthContoller.ts
> +import * as AuthService from '../service/AuthService';
미안하다 매우

2023-11-05 15:52 UTC, SEOKKAMONI commented on src/service/AuthService.ts
> +  const authCode = req.query.code;
```tsx
{ req: { query } } : Request
```
이것은 생각한다 안좋다고 가독성이 어떻게 생각하나..

2023-11-05 15:53 UTC, SEOKKAMONI commented on src/service/AuthService.ts
> +  const authCode = req.query.code;
const {code} = req.query를 말하는거냐..? 궁금하다 나는

2023-11-05 15:53 UTC, SEOKKAMONI commented on src/service/AuthService.ts
> +        let userRole: Role = 'STUDENT';
고맙다 당신은 천사다

2023-11-05 15:54 UTC, SEOKKAMONI commented on src/service/AuthService.ts
> +      }
고맙다 매우

2023-11-05 15:55 UTC, SEOKKAMONI commented on src/controller/AuthContoller.ts
> +router.post('/', AuthService.loginUser);
그럼 어떤식으로 하는게 좋을까 줘라 솔루션 나는 한다 부탁..

2023-11-05 15:56 UTC, qlido commented on src/service/AuthService.ts
> +  const authCode = req.query.code;
yes, req.code.query have string | string[] | undefined and something.
So, destructuring makes you more easy type handling

2023-11-05 15:58 UTC, SEOKKAMONI commented on src/service/AuthService.ts
> +  const authCode = req.query.code;
하지만 code는 명시적인 네이밍이라고 생각되지않는다 나는 필요하다 더욱 더 명시적인 네이밍

2023-11-05 15:59 UTC, SEOKKAMONI commented on prisma/schema.prisma
> +  id          Int     @id @unique
유니크해서 박은거였는데.. 문제가 있나?.. 궁금하다 나는

2023-11-05 16:03 UTC, qlido commented on prisma/schema.prisma
> +  id          Int     @id @unique
@Id already has unique Constraint

2023-11-05 16:04 UTC, SEOKKAMONI commented on prisma/schema.prisma
> +  id          Int     @id @unique
오 몰랐다 당신은 천재다 가라 신한은행

2023-11-05 16:04 UTC, qlido commented on src/service/AuthService.ts
> +  const authCode = req.query.code;
Then you have to fill out a type test expression

2023-11-05 16:05 UTC, qlido commented on src/service/AuthService.ts
> +  const authCode = req.query.code;
other way, you send code in frontend you can change naming code to authCode

2023-11-05 16:07 UTC, qlido commented on src/controller/AuthContoller.ts
> +router.post('/', AuthService.loginUser);
```ts
const controller = (req,res,next) => {
    const {asdf,asdff} = req.body;
    service.login(asdf,asdff);
    return res.send(something)
}
```

2023-11-05 16:08 UTC, SEOKKAMONI commented on src/controller/AuthContoller.ts
> +router.post('/', AuthService.loginUser);
당신은 천재..

2023-11-05 16:12 UTC, qlido commented on src/service/AuthService.ts
> +const BSM_AUTH_CLIENT_SECRET = process.env.CLIENT_SECRET || '';
PS. i think detach env file is better

2023-11-05 16:45 UTC, SEOKKAMONI commented on src/controller/AuthContoller.ts
> +import * as AuthService from '../service/AuthService';
나중에 따로 이슈를 생성해서 하겠다.

2023-11-05 16:47 UTC, SEOKKAMONI commented on src/service/AuthService.ts
> +    }
```suggestion
    }       
    return next(new InternalServerException());
```

2023-11-05 16:47 UTC, SEOKKAMONI commented on src/service/AuthService.ts
> +      }
```suggestion
      }
      return next(new ForbiddenException());
```

2023-11-05 16:48 UTC, qlido approved these changes
Good!

2023-11-05 16:48 UTC, qlido commented on src/service/AuthService.ts
> +        return next(new ForbiddenException());
why next? next in Controller

2023-11-05 16:49 UTC, SEOKKAMONI commented on src/service/AuthService.ts
> +        return next(new ForbiddenException());
ok

2023-11-05 23:27 UTC, qlido requested changes

2023-11-05 23:27 UTC, qlido commented on src/service/AuthService.ts
> +      data: { accessToken: jwtToken, refreshToken: jwtToken },
?

2023-11-05 23:27 UTC, qlido commented on src/service/AuthService.ts
> +    const semester = enrolledAt - 2020;
??? 지랄

2023-11-05 23:27 UTC, qlido commented on src/controller/AuthContoller.ts
> +  }
에러 핸들링 라우터는 어디있나요

2023-11-05 23:44 UTC, SEOKKAMONI commented on src/controller/AuthContoller.ts
> +  }
맞는지 모르겠네요

2023-11-05 23:44 UTC, SEOKKAMONI commented on src/service/AuthService.ts
> +      data: { accessToken: jwtToken, refreshToken: jwtToken },
뭐여

2023-11-06 01:15 UTC, qlido requested changes

2023-11-06 01:15 UTC, qlido commented on src/controller/AuthContoller.ts
> +  if (!code) return generateError({ status: 400, message: '잘못된 요청' });
왜 인자를 object로 정의하심

2023-11-06 01:15 UTC, qlido commented on src/controller/AuthContoller.ts
> +  const response = await AuthService.loginUser(code as string);
쿼리를 쓰는 이유

2023-11-06 01:15 UTC, qlido commented on src/middleware/errorHandler.ts
> +};
이게 무슨 의도인지 모르겠습니다

2023-11-06 01:15 UTC, qlido commented on src/service/AuthService.ts
> +    const refreshToken = jwt.sign({ userCode }, JWT_SCRECT_KEY, { expiresIn: '30d' });
이럴꺼면 refresh 왜 쓰시나요

2023-11-06 03:43 UTC, SEOKKAMONI commented on src/middleware/errorHandler.ts
> +};
모듈화

2023-11-06 03:43 UTC, SEOKKAMONI commented on src/controller/AuthContoller.ts
> +  const response = await AuthService.loginUser(code as string);
다 쓰길래

2023-11-06 03:51 UTC, SEOKKAMONI commented on src/controller/AuthContoller.ts
> +  if (!code) return generateError({ status: 400, message: '잘못된 요청' });
매개변수가 함수 밖에 보임으로써 좀 더 명시적이라고 생각하였고

```ts
let response = {
  message: "안녕",
  status: 200
}

if(석진은 잘생김) {
response = {
  message: "인정",
  status: 200
}
}

generateError(response)
```

다음과 같이 사용될수도있기에

2023-11-06 10:48 UTC, merged